export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGOUT_USER = 'LOGOUT_USER';
export const TURN_ON_NOTIFICATION = 'TURN_ON_NOTIFICATION';
export const TURN_OF_NOTIFICATION = 'TURN_OF_NOTIFICATION';
